#! /bin/bash
# Copyright (c) 2014 Ciseco.
# All rights reserved.
#
# Author: Matt Lloyd
#
# /etc/init.d/llapserver
#
### BEGIN INIT INFO
# Provides: llapserver
# Required-Start: $remotefs $syslog
# Required-Stop: $remotefs $syslog
# Default-Start:  2 3 4 5
# Default-Stop:   0 1 6
# Short-Description: LLAP Translator service
# Description:    LLAP Translator service to pass LLAP trafic between serial and UDP intrefaces
### END INIT INFO

###
# This line will be auto updated with the path to your current install path
# by LLAPLauncher on clicking the Enable Autostart button
cd /home/pi/LLAPServer
###

case "$1" in
  start)
    echo "Starting translator"
    python ./LLAPServer.py start
    ;;
  stop)
    echo "Stopping translator"
    python ./LLAPServer.py stop
    ;;
  restart)
    echo "Restarting translator"
    python ./LLAPServer.py restart
    ;;
  *)
    # Igonre everything else
    echo "Usage: /etc/init.d/llapserver {start|stop|restart}"
    exit 1
    ;;
esac

exit 0
