#! /bin/bash
# Copyright (c) 2014 Ciseco.
# All rights reserved.
#
# Author: Matt Lloyd
#
# /etc/init.d/messagebridge
#
### BEGIN INIT INFO
# Provides: messagebridge
# Required-Start: $remotefs $syslog
# Required-Stop: $remotefs $syslog
# Default-Start:  2 3 4 5
# Default-Stop:   0 1 6
# Short-Description: Wireless Things Message Bridge
# Description:    Wireless Things Message Bridge to pass Language of Things trafic between serial and UDP interfaces
### END INIT INFO

###
# This line will be auto updated with the path to your current install path
# by Wireless Things Launchpad on clicking the Enable Autostart button
cd /home/pi/MessageBridge
###

case "$1" in
  start)
    echo "Starting Message Bridge"
    python ./MessageBridge.py start
    ;;
  stop)
    echo "Stopping Message Bridge"
    python ./MessageBridge.py stop
    ;;
  restart)
    echo "Restarting Message Bridge"
    python ./MessageBridge.py restart
    ;;
  *)
    # Ignore everything else
    echo "Usage: /etc/init.d/messagebridge {start|stop|restart}"
    exit 1
    ;;
esac

exit 0
