#! /bin/bash
# Copyright (c) 2014 Ciseco.
# All rights reserved.
#
# Author: Matt Lloyd
#
# /etc/init.d/llapserver
#
### BEGIN INIT INFO
# Provides: llapserver
# Required-Start: 
# Should-Start: 
# Required-Stop: 
# Should-Stop:
# Default-Start:  3 5
# Default-Stop:   0 1 2 6
# Short-Description: LLAP Translator service
# Description:    LLAP Translator service to pass LLAP trafic between serial and UDP intrefaces
### END INIT INFO

cd /home/pi/LLAPServer

case "$1" in
  start)
    echo "Starting translator"
    python /home/pi/LLAPServer/LLAPServer.py start
    ;;
  stop)
    echo "Stopping translator"
    python /home/pi/LLAPServer/LLAPServer.py stop
    ;;
  restart)
    echo "Restarting translator"
    python /home/pi/LLAPServer/LLAPServer.py restart
    ;;
  *)
    # Igonre everything else
    echo "Usage: /etc/init.d/llapserver {start|stop|restart}"
    exit 1
    ;;
esac

exit 0
